version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo:/data/db
  redis:
    image: redis:7.0.5-alpine
    container_name: redis
    ports:
      - '6379:6379'

volumes:
  mongo:
